title: Audit Data Analysis
description: Documentation supporting the book
theme: just-the-docs

# If GitHub Pages complains about 'theme' not found, use this instead:
remote_theme: just-the-docs/just-the-docs

# Optional: enable search
search_enabled: true

# Optional: set your base path if your site is not at the root
# (your repo is luhoo.github.io/audit-data-analysis, so set the baseurl)
baseurl: "/audit-data-analysis"